image: ruby:2.3

pages:
  stage: deploy
  script:
  - gem install bundler
  - gem install jekyll
  - bundle update
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
